site_name: Desarrollo Web en Entorno Cliente
nav:
  - "Inicio": "index.md"
  - "Planificación": "planificacion.md"
  - "UT 1. Selección de arquitecturas y herramientas de programación":
      - "1. Desarrollo de Software": "ut1-seleccionarquitecturasyherramientasprogramacion/1desarrollodesoftware.md"
      - "2. Tipos de aplicaciones": "ut1-seleccionarquitecturasyherramientasprogramacion/2tiposdeaplicaciones.md"
      - "3. Desarrollo de aplicaciones Web": "ut1-seleccionarquitecturasyherramientasprogramacion/3desarrollodeaplicacionesweb.md"
      - "4. Entorno de desarrollo": "ut1-seleccionarquitecturasyherramientasprogramacion/4entornodedesarrollo.md"
      - "5. Integrar código JavaScript en HTML": "ut1-seleccionarquitecturasyherramientasprogramacion/5integrarcodigojsenhtml.md"
      - "6. Recursos y FAQ": "ut1-seleccionarquitecturasyherramientasprogramacion/6recursosyfaq.md"
  - "UT 2. Manejo de la sintaxis del lenguaje":
      - "1. Variables": "ut2-manejo-de-la-sintaxis-del-lenguaje/1variables.md"
      - "2. Tipos de Datos": "ut2-manejo-de-la-sintaxis-del-lenguaje/2tiposdedatosyconversiones.md"
      - "3. Asignaciones": "ut2-manejo-de-la-sintaxis-del-lenguaje/3asignaciones.md"
      - "4. Operadores": "ut2-manejo-de-la-sintaxis-del-lenguaje/4operadores.md"
      - "5. Comentarios": "ut2-manejo-de-la-sintaxis-del-lenguaje/5comentarios.md"
      - "6. Condicionales": "ut2-manejo-de-la-sintaxis-del-lenguaje/6condicionales.md"
      - "7. Bucles": "ut2-manejo-de-la-sintaxis-del-lenguaje/7bucles.md"
      - "8. Funciones": "ut2-manejo-de-la-sintaxis-del-lenguaje/8funciones.md"
      - "9. Arrays": "ut2-manejo-de-la-sintaxis-del-lenguaje/9objetosyarrays.md"
      - "10. Clases": "ut2-manejo-de-la-sintaxis-del-lenguaje/10clases.md"
      - "11. Recursos y FAQ": "ut2-manejo-de-la-sintaxis-del-lenguaje/11recursosyfaq.md"
  - "UT 3. Objetos predefinidos del lenguaje": 
      - "1. Introducción a los Objetos Predefinidos": "ut3-objetos-predefinidos-del-lenguaje/1introduccion.md"
      - "2. Objetos Nativos del Lenguaje": "ut3-objetos-predefinidos-del-lenguaje/2objetosnativosdellenguaje.md"

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
plugins:
  - search:
      lang: es
  - glightbox

theme:
  name: material
  features:
    - navigation.footer
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Quitar modo oscuro
extra_css:
  - stylesheets/extra.css
extra:
  analytics:
    provider: google
    property: G-3VWRJDCQS9
    feedback:
      title: <a href='https://ko-fi.com/jgarciadeparedesh02' title='Invítame a un café en ko-fi.com' target='_blank'><img height='36' style='border:0px;height:36px;' src='https://storage.ko-fi.com/cdn/kofi2.png?v=3' border='0' alt='Invítame a un café en ko-fi.com' /></a>
      ratings:
        - icon: material/emoticon-happy-outline
          name: Esta página es genial
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: Podría mejorar
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.